### ISSUE TITLE
Logic flow between screens result in persistent panel instruments

### ISSUE THREAD

**Issue by developingAlex** [isnology/project-foxbat#5]
State of users panel config seems to persist when you wouldn't intuitively expect it to
To reproduce:
- start from the home screen and don't sign in.
- go to the a22 6pack panel and place some instruments in the slots
- never save it
- click the clear panel button
- click the go to start button
- navigate to the a32 6pack panel and you will see the instruments that you thought you cleared from a different panel appear slotted into this one.

It should be expected that upon clearing all instruments, going to the start again, and selecting a completely different plane, it wouldn't intuitively be assumed that your instruments would reappear given that you pressed the clear panel button.

**Comment by piratechicken** [comment]
It must be persisting in the local storage. I will check... @isnology, can you have a look too?

**Comment by piratechicken** [comment]
PS. good pick up.

**Comment by developingAlex** [comment]
this issue was resolved by @isnology , the cause was assigning a state object variable to another object, instead of cloning the other object, as a result it pointed to the same location and those values were subsequently modified by the user when it was meant to stand as a constant and reference value only.
